// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "LinkedHashtagsService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::thriftService;

class LinkedHashtagsServiceHandler : virtual public LinkedHashtagsServiceIf {
 public:
  LinkedHashtagsServiceHandler() {
    // Your initialization goes here
  }

  void thriftGenerateGraphData(Output& _return, const Input& tweetList, const IOutput& oldGraph, const FreewordList& freewordList) {
    // Your implementation goes here
    printf("thriftGenerateGraphData\n");
  }

  bool thriftCreatStream(const std::string& id, const FreewordList& freewordList) {
    // Your implementation goes here
    printf("thriftCreatStream\n");
  }

  bool thriftAddNewTweets(const std::string& id, const Input& tweetList) {
    // Your implementation goes here
    printf("thriftAddNewTweets\n");
  }

  bool thriftStreamDone(const std::string& id) {
    // Your implementation goes here
    printf("thriftStreamDone\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<LinkedHashtagsServiceHandler> handler(new LinkedHashtagsServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new LinkedHashtagsServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

