// UI
export const TOGGLE_STREAMING = 'TOGGLE_STREAMING';
export const TOGGLE_ACCOUNT_FORM_DIALOG = 'TOGGLE_ACCOUNT_FORM_DIALOG';
export const SWITCH_ACCOUNT_FORM = 'SWITCH_ACCOUNT_FORM';
export const TOGGLE_EXPORT_DIALOG = 'TOGGLE_EXPORT_DIALOG';
export const TOGGLE_IMPORT_DIALOG = 'TOGGLE_IMPORT_DIALOG';
export const TOGGLE_UPGRADE = 'TOGGLE_UPGRADE';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
export const UPDATE_SNACKBAR = 'UPDATE_SNACKBAR';
export const TOGGLE_NODE_ACTIONS = 'TOGGLE_NODE_ACTIONS';
export const TOGGLE_EDGE_DATA_CARD = 'TOGGLE_EDGE_DATA_CARD';
export const SET_EDGE_DATA = 'SET_EDGE_DATA';
export const RESET_EDGE_DATA = 'RESET_EDGE_DATA';
export const SORT_HASHTAG_LIST = 'SORT_HASHTAG_LIST';
export const CHOOSE_FILE = 'CHOOSE_FILE';
export const UPLOAD_FILE = 'UPLOAD_FILE'; // also HashtagGraph
export const TOGGLE_PARAMS_FORM = 'TOGGLE_PARAMS_FORM';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_STREAM_DIALOG = 'TOGGLE_STREAM_DIALOG';
export const TOGGLE_HISTORY_DIALOG = 'TOGGLE_HISTORY_DIALOG';
export const TOGGLE_TOOLBAR = 'TOGGLE_TOOLBAR';
export const TOGGLE_GRAPH_PARAMS = 'TOGGLE_GRAPH_PARAMS';
export const TOGGLE_GRAPH_FILTERS = 'TOGGLE_GRAPH_FILTERS';
export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
export const TOGGLE_INFO_DIALOG = 'TOGGLE_INFO_DIALOG';
export const TOGGLE_USERS_DIALOG = 'TOGGLE_USERS_DIALOG';
export const TOGGLE_SORT_HL = 'TOGGLE_SORT_HL';
export const TOGGLE_ANALYTICS_PANEL = 'TOGGLE_ANALYTICS_PANEL';
export const RESET_GRAPH_CAMERA = 'RESET_GRAPH_CAMERA';
export const SET_TWEETS = 'SET_TWEETS';
export const TOGGLE_EVENT_DATA = 'TOGGLE_EVENT_DATA';
export const SET_EVENT_HASHTAG_LIST = 'SET_EVENT_HASHTAG_LIST';
export const TWEET_CHCKED = 'TWEET_CHCKED';
export const CHANGE_TWEET_EVENT_CARD = 'CHANGE_TWEET_EVENT_CARD';
export const RESET_EVENT_STORE = 'RESET_EVENT_STORE';
export const SET_LEVEL1_COUNT = 'SET_LEVEL1_COUNT';
export const SET_LEVEL2_COUNT = 'SET_LEVEL2_COUNT';
export const CHANGE_VIEW_TWEET = 'CHANGE_VIEW_TWEET';
export const TOGGLE_HEATMAP = 'TOGGLE_HEATMAP';
export const CHANGE_HEATMAP_MODE = 'CHANGE_HEATMAP_MODE';
export const CHANGE_IS_FUZZY = 'CHANGE_IS_FUZZY';
export const CHANGE_IS_DASHBORD_MODE = 'CHANGE_IS_DASHBORD_MODE';
// HashtagGraph
export const SET_MIN_WEIGHT_FILTER = 'SET_MIN_WEIGHT_FILTER';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const TOGGLE_SELECT_ALL = 'TOGGLE_SELECT_ALL';
export const TOGGLE_HIGHLIGHT_SELECTED = 'TOGGLE_HIGHLIGHT_SELECTED';
export const TOGGLE_HIDE_SELECTED = 'TOGGLE_HIDE_SELECTED';
export const SELECT_HASHTAG = 'SELECT_HASHTAG';
export const HIGHLIGHT_HASHTAG = 'HIGHLIGHT_HASHTAG';
export const SHOW_HASHTAG_NEIGHBORS = 'SHOW_HASHTAG_NEIGHBORS';
export const HIDE_HASHTAG = 'HIDE_HASHTAG';
export const REFRESH_GRAPH = 'REFRESH_GRAPH';
export const SET_GRAPH_LAYOUT = 'SET_GRAPH_LAYOUT';
export const GENERATE_GRAPH_DATA = 'GENERATE_GRAPH_DATA';
export const UPDATE_CURRENT_QUERY = 'UPDATE_CURRENT_QUERY';
export const GENERATE_STREAM_GRAPH = 'GENERATE_STREAM_GRAPH';
export const RESET_HASHTAG_GRAPH = 'RESET_HASHTAG_GRAPH';

// Account
export const CREATE_USER = 'CREATE_USER';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_API_KEY = 'CHANGE_API_KEY';

// Jobs
export const CREATE_JOB = 'CREATE_JOB';
export const SET_STREAM_JOB_ID = 'SET_STREAM_JOB_ID';
export const SET_CURRENT_JOB = 'SET_CURRENT_JOB';
export const CONTROL_JOB = 'CONTROL_JOB';
export const RESET_CURRENT_JOB = 'RESET_CURRENT_JOB';

// Users
export const TOGGLE_USER_ROLE = 'TOGGLE_USER_ROLE';
export const SET_USER_ROLES = 'SET_USER_ROLES';
